import {z} from 'zod';

export interface AppDescription {
  appName: string;
  description: string;
  features?: string[];
  apiVersion:string;
  baseUrl?: string;
}

export interface SwaggerSpec {
  openapi: string;
  info: {
    title: string;
    version: string;
    description?: string;
  };
  paths: Record<string, any>;
  [key:string]: any;
}

export interface GeneratedResponse {
  success: boolean;
  specification: SwaggerSpec;
  metadata: {
    generatedAt: string;
    inputData: AppDescription;
    tokenUsed: number;
  }
}

export class SwaggerParseError extends Error {
  constructor(message: string, public originalError?: Error) {
    super(message);
    this.name = 'SwaggerParseError';
  }
}

export class SwaggerGeneratorModel {
  // Validation schema for app description
  private static readonly AppDescriptionSchema = z.object({
    appName: z.string().min(1, 'App name is required'),
    description: z.string().min(10, 'Description must be at least 10 characters'),
    features: z.array(z.string()).optional().default([]),
    apiVersion: z.string().default('1.0.0'),
    baseUrl: z.string().optional(),
  });

  // Validation schema for basic OpenAPI structure
  private static readonly SwaggerSpecSchema = z.object({
    openapi: z.string(),
    info: z.object({
      title: z.string(),
      version: z.string(),
      description: z.string().optional(),
    }),
    paths: z.record(z.any()),
  }).passthrough(); // Allow additional properties

  // Supported features list
  public static SUPPORTED_FEATURES = [
    'Authentication (JWT, OAuth)',
    'CRUD Operations',
    'File Upload/Download',
    'Real-time Updates',
    'Payment Processing',
    'User Management',
    'Search & Filtering',
    'Notifications',
    'Analytics & Reporting',
    'Third-party Integrations',
  ] as const;

  // Supported HTTP methods
  public static readonly SUPPORTED_METHODS = [
    'GET', 'POST', 'PUT', 'DELETE', 'PATCH'
  ] as const;

      // Supported authentication types
  public static readonly SUPPORTED_AUTH_TYPES = [
    'Bearer Token', 'API Key', 'OAuth 2.0'
  ] as const;

  /**
   * Validates app description input
   */
  public static validateAppDescription(data: unknown): AppDescription {
    return this.AppDescriptionSchema.parse(data);
  }

  /**
   * Parses and validates generated swagger specification
   */
  public static parseSwaggerSpec(jsonText: string): SwaggerSpec {
    try {
      const parsed = JSON.parse(jsonText);
      return this.SwaggerSpecSchema.parse(parsed);
    } catch (error) {
      if (error instanceof SyntaxError) {
        throw new SwaggerParseError('Invalid JSON format generated by AI', error);
      }
      if (error instanceof z.ZodError) {
        throw new SwaggerParseError('Generated specification missing required OpenAPI fields');
      }
      throw new SwaggerParseError('Failed to parse swagger specification', error as Error);
    }
  }

  /**
   * Type guard for Zod validation errors
   */
  public static isValidationError(error: unknown): error is z.ZodError {
    return error instanceof z.ZodError;
  }  

  /**
   * Type guard for swagger parse errors
   */
  public static isSwaggerParseError(error: unknown): error is SwaggerParseError {
    return error instanceof SwaggerParseError;
  }

  /**
   * Creates a sanitized app description with defaults
   */
  public static createAppDescription(data: Partial<AppDescription>): AppDescription {
    return {
      appName: data.appName || 'Untitled App',
      description: data.description || 'A web application',
      features: data.features || [],
      apiVersion: data.apiVersion || '1.0.0',
      baseUrl: data.baseUrl,
    };
  }

  /**
    * Validates if a feature is supported
    */
  public static isSupportedFeature(feature: string): boolean {
    return this.SUPPORTED_FEATURES.includes(feature as any);
  }

  /**
   * Filters and returns only supported features
   */
  public static filterSupportedFeatures(features: string[]): string[] {
    return features.filter(feature => this.isSupportedFeature(feature));
  }

  /**
   * Gets feature summary for prompt generation
   */
  public static getFeatureSummary(features: string[]): string {
    const supportedFeatures = this.filterSupportedFeatures(features);
    return supportedFeatures.length > 0 
      ? supportedFeatures.join(', ') 
      : 'Basic CRUD operations';
  }

  /**
   * Validates swagger specification structure
   */
  public static validateSwaggerStructure(spec: unknown): spec is SwaggerSpec {
    try {
      this.SwaggerSpecSchema.parse(spec);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Counts endpoints in a swagger specification
   */
  public static countEndpoints(spec: SwaggerSpec): number {
    return Object.keys(spec.paths || {}).length;
  }

  /**
   * Extracts HTTP methods from swagger specification
   */
  public static extractHttpMethods(spec: SwaggerSpec): string[] {
    const methods = new Set<string>();
    
    Object.values(spec.paths || {}).forEach(pathItem => {
      if (typeof pathItem === 'object' && pathItem !== null) {
        Object.keys(pathItem).forEach(method => {
          if (this.SUPPORTED_METHODS.includes(method.toUpperCase() as any)) {
            methods.add(method.toUpperCase());
          }
        });
      }
    });
    
    return Array.from(methods);
  }
}

